config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "crafts#index"
  resources :crafts
  get 'shop', to: 'crafts#shop'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/craft.rb
class Craft < ApplicationRecord
  has_one_attached :image

  def thumbnail
    return self.image.variant(resize: '300x300!')
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crafts_controller.rb
class CraftsController < ApplicationController
  
  def index
    @crafts = Craft.all
  end

  def new
    @craft = Craft.new
  end

  def create
    Craft.create(craft_params)
    redirect_to root_path
  end

  def show
    @craft = Craft.find(params[:id])
  end

  def edit
    @craft = Craft.find(params[:id])
  end

  def update
    @craft = Craft.find(params[:id])
    @craft.update_attributes(craft_params)
    redirect_to root_path
  end

  def destroy
    @craft = Craft.find(params[:id])
    @craft.destroy
    redirect_to root_path
  end
  def shop
    @crafts = Craft.all
  end

  private

  def craft_params
    params.require(:craft).permit(:name, :description, :quantity, :option, :cost, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crafts_helper.rb
module CraftsHelper
end

app/views/crafts/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Craft</h1>
  <%= simple_form_for @craft do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/crafts/index.html.erb
<div class="booyah-box col-10 offset-1">


<h1>Featured Crafts</h1>
<br />
  <div class="row">
    <% @crafts.each do |craft| %>
      <div class="booyah-box">
        <h2><%= link_to craft.name, craft_path(craft) %></h2>
        <p><%= craft.cost %></p>
        <%= image_tag(craft.thumbnail) %>

      </div>
    <% end %>
  </div> 


<h1>Coming Soon</h1>
</div>

app/views/crafts/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Craft Details</h1>
  <%= simple_form_for @craft do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/crafts/shop.html.erb
<h1>Shop Now</h1>
<br />

  <div class="row">
    <% @crafts.each do |craft| %>
      <div class="col-3">
        <h2><%= link_to craft.name, craft_path(craft) %></h2>
        <p><%= craft.cost %></p>
        <%= image_tag(craft.thumbnail) %>

      </div>
    <% end %>
  </div> 

app/views/crafts/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1><%= @craft.name %></h1>
  <p><%= @craft.description %></p>
  <p><%= @craft.cost %></p>
  <%= image_tag(@craft.thumbnail) %>

  <div class="float-right">
    <%= link_to 'Edit', edit_craft_path(@craft), class: 'btn btn-primary' %>
    <%= link_to 'Delete', craft_path(@craft), remote: true, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wishfulcrafts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'WishfulCrafts', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Shop All', shop_path, class: 'nav-link' %>
        </li>      
        <li class="nav-item">
          <%= link_to 'New Craft', new_craft_path, class: 'nav-link' %>
        </li>
        <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete,  class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>


    <%= yield %>
  </body>
</html>